### ISSUE TITLE
iOS: Schedule screen > select History of Anaesthesia and app goes to the History of Anaesthesia screen however there is no back arrow to go back to schedule or menu screen. 

### ISSUE THREAD

**Issue by SANJMATHIAS** [1hf/misacon#6]

**Comment by SANJMATHIAS** [comment]
If I slide the screen to the right I am able to go back to the main screen. However no indication shown to the user to do that.

**Comment by prabagar-mk** [comment]
Back arrow added in the schedule details page to go to the previous list page.
